import { readFile, writeFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import { join, resolve } from "node:path";
import { defineConfig, type Plugin } from "vite";
import jiabaPackage from "./node_modules/jieba-wasm/package.json" with { type: "json" };
import pkg from "./package.json" with { type: "json" };

const jiebaVersion = jiabaPackage.version;

const builtins = [...builtinModules, "original-fs"].flatMap((mod) => [
  mod,
  `node:${mod}`,
]);

const jsBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source visit the plugin's github repository
*/
`;

export default defineConfig(({ mode }) => {
  const isProd = mode === "production";

  return {
    define: {
      "process.env.NODE_ENV": JSON.stringify(
        isProd ? "production" : "development",
      ),
      __JIEBA_VERSION__: JSON.stringify(jiebaVersion),
    },
    build: {
      lib: {
        entry: resolve(import.meta.dirname, "src/chsp-main.ts"),
        formats: ["cjs"],
        fileName: () => "main.js",
      },
      outDir: "build",
      emptyOutDir: false,
      sourcemap: isProd ? false : "inline",
      minify: isProd,
      target: "es2022",
      copyPublicDir: false,
      rollupOptions: {
        external: [
          "obsidian",
          "electron",
          "@electron/remote",
          "@codemirror/state",
          "@codemirror/view",
          ...builtins,
        ],
        output: {
          banner: jsBanner,
        },
      },
    },
    plugins: [obsidianBuildPlugin({ hotreload: !isProd })],
  };
});

function obsidianBuildPlugin({ hotreload }: { hotreload: boolean }): Plugin {
  return {
    name: "obsidian-build",
    async writeBundle(options) {
      const outDir = options.dir ?? "build";
      // Stamp the release version (release-it bumps package.json, including
      // pre-releases) onto the manifest so betas don't need a separate file.
      const manifest = JSON.parse(await readFile("manifest.json", "utf8"));
      manifest.version = pkg.version;
      await writeFile(
        join(outDir, "manifest.json"),
        `${JSON.stringify(manifest, null, 2)}\n`,
      );
      if (hotreload) {
        await writeFile(join(outDir, ".hotreload"), "").catch((err) => {
          if (err.code !== "EEXIST") throw err;
        });
      }
    },
  };
}
