import { cp, writeFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import { join, resolve } from "node:path";
import { defineConfig, type Plugin } from "vite";
import jiabaPackage from "./node_modules/jieba-wasm/package.json" with { type: "json" };

const jiebaVersion = jiabaPackage.version;

const builtins = [...builtinModules, "original-fs"].flatMap((mod) => [
  mod,
  `node:${mod}`,
]);

const jsBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source visit the plugin's github repository
*/
`;

export default defineConfig(({ mode }) => {
  const isProd = mode === "production";
  const isBeta = mode === "beta";

  return {
    define: {
      "process.env.NODE_ENV": JSON.stringify(
        isProd ? "production" : "development",
      ),
      __JIEBA_VERSION__: JSON.stringify(jiebaVersion),
    },
    build: {
      lib: {
        entry: resolve(import.meta.dirname, "src/chsp-main.ts"),
        formats: ["cjs"],
        fileName: () => "main.js",
      },
      outDir: "build",
      emptyOutDir: false,
      sourcemap: isProd || isBeta ? false : "inline",
      minify: isProd || isBeta,
      target: "es2022",
      copyPublicDir: false,
      rollupOptions: {
        external: [
          "obsidian",
          "electron",
          "@electron/remote",
          "@codemirror/state",
          "@codemirror/view",
          ...builtins,
        ],
        output: {
          banner: jsBanner,
        },
      },
    },
    plugins: [
      obsidianBuildPlugin({ beta: isBeta, hotreload: !isProd && !isBeta }),
    ],
  };
});

function obsidianBuildPlugin({
  beta,
  hotreload,
}: {
  beta: boolean;
  hotreload: boolean;
}): Plugin {
  return {
    name: "obsidian-build",
    async writeBundle(options) {
      const outDir = options.dir ?? "build";
      const manifestSrc = beta ? "manifest-beta.json" : "manifest.json";
      await cp(manifestSrc, join(outDir, "manifest.json"));
      if (hotreload) {
        await writeFile(join(outDir, ".hotreload"), "").catch((err) => {
          if (err.code !== "EEXIST") throw err;
        });
      }
    },
  };
}
